compass-name: "ยง6Minigame Navigator"
compass-give-on-join: true

minigames:
  BedWars:
    material: "DIAMOND_SWORD"
    command: "startbedwars %player%"
  SkyWars:
    material: "FEATHER"
    command: "startskywars %player%"
  Survival:
    material: "IRON_SWORD"
    command: "startsurvival %player%"
