name: MinigameCompass
main: herr_rotstein.minigamecompass.CompassMinigamesMain
version: 1.0
api-version: 1.20
author: herr_rotstein
commands:
  reloadcompass:
    description: Lädt die Config neu
    usage: /reloadcompass
    permission: minigamecompass.reload
